from cocotb.queue import Queue
import cocotb
from cocotb.clock import Clock
from cocotb.triggers import RisingEdge, ClockCycles, ReadOnly

from enum import IntEnum

class ALUOp(IntEnum):
    ADD = 0
    SUB = 1
    AND = 2
    OR  = 3

class Transaction:
    def __init__(self,a=0,b=0,op_code=ALUOp.ADD,rst=0):
        # inputs
        self.a = a
        self.b = b
        self.op_code = op_code
        self.rst = rst
        # ouputs 
        self.result = 0
        self.z = 0
        self.n = 0
        self.c = 0
        self.v = 0
    def __repr__(self):
        return (
            f"Transaction("
            f"a={self.a}, "
            f"b={self.b}, "
            f"op={self.op_code.name}, "
            f"rst={self.rst}, "
            f"result={self.result}, "
            f"z={self.z}, "
            f"n={self.n}, "
            f"c={self.c}, "
            f"v={self.v})"
        )



class Driver:
    def __init__ (self,dut):
        self.dut = dut
        self.seq_item_port = Queue(); 
    async def reset_driving(self):
        self.dut.rst.value = 0
        await RisingEdge(self.dut.clk)
        self.dut.rst.value = 1
        self.dut.a.value = 0
        self.dut.b.value = 0
        self.dut.op_code.value = 0
        await RisingEdge(self.dut.clk)
        self.dut.rst.value = 0
        await RisingEdge(self.dut.clk)
        self.dut._log.info("RESET_DONE")

    async def run(self):
        while True:
            trans = await self.seq_item_port.get()

            self.dut.a.value = trans.a
            self.dut.b.value = trans.b
            self.dut.op_code.value = trans.op_code
            self.dut.rst.value = trans.rst
            
            await RisingEdge(self.dut.clk)

class Monitor:
    def __init__ (self ,dut):
        self.dut = dut
        self.analysis_port = Queue()

    async def run(self):
        while True:
            # ── Step 1: sample inputs on the cycle they are driven ──
            await RisingEdge(self.dut.clk)
            await ReadOnly()

            # skip if any signal is unknown
            signals = [self.dut.rst, self.dut.a, self.dut.b, self.dut.op_code]
            unknown = False
            for sig in signals:
                if not sig.value.is_resolvable:
                    self.dut._log.error(f"Monitor: {sig._name} contains X/Z")
                    unknown = True
            if unknown:
                continue

            # capture inputs NOW
            trans = Transaction()
            trans.rst     = int(self.dut.rst.value)
            trans.a       = self.dut.a.value.to_signed()
            trans.b       = self.dut.b.value.to_signed()
            trans.op_code = ALUOp(int(self.dut.op_code.value))

            # ── Step 2: wait one cycle for the output to appear ──
            await RisingEdge(self.dut.clk)
            await ReadOnly()

            # check output signals
            out_signals = [self.dut.result, self.dut.z, self.dut.n, self.dut.c, self.dut.v]
            for sig in out_signals:
                if not sig.value.is_resolvable:
                    self.dut._log.error(f"Monitor: {sig._name} contains X/Z")
                    unknown = True
            if unknown:
                continue

            # capture outputs NOW — they correspond to the inputs above
            trans.result = self.dut.result.value.to_signed()
            trans.z      = int(self.dut.z.value)
            trans.n      = int(self.dut.n.value)
            trans.c      = int(self.dut.c.value)
            trans.v      = int(self.dut.v.value)

            self.dut._log.info(f"Monitor: {trans}")
            await self.analysis_port.put(trans)

class Scoreboard:
    def __init__(self):
        self.analysis_export = Queue()

    async def run (self):
        while True:
            # Wait for a transaction from the monitor
            txn = await self.analysis_export.get()

            cocotb.log.info(f"Scoreboard received: {txn}")

            # Compute expected result
            exp_result, exp_z, exp_n, exp_c, exp_v = self.reference_model(txn)

            # Compare
            assert txn.result == exp_result, \
                f"RESULT mismatch: Expected={exp_result}, Got={txn.result}"

            assert txn.z == exp_z, \
                f"Z mismatch: Expected={exp_z}, Got={txn.z}"

            assert txn.n == exp_n, \
                f"N mismatch: Expected={exp_n}, Got={txn.n}"

            assert txn.c == exp_c, \
                f"C mismatch: Expected={exp_c}, Got={txn.c}"

            assert txn.v == exp_v, \
                f"V mismatch: Expected={exp_v}, Got={txn.v}"

            cocotb.log.info("Scoreboard: Transaction Passed")
    def reference_model(self, txn): ## Generated by AI 

        WIDTH = 4
        MASK = (1 << WIDTH) - 1

        # -----------------------
        # Reset
        # -----------------------
        if txn.rst:
            return 0, 1, 0, 0, 0

        # -----------------------
        # Convert to 4-bit values
        # -----------------------
        a = txn.a & MASK
        b = txn.b & MASK

        c = 0
        v = 0

        # -----------------------
        # Operation
        # -----------------------
        if txn.op_code == ALUOp.ADD:

            full = a + b
            c = (full >> WIDTH) & 1
            result = full & MASK

            sign_a = (a >> (WIDTH - 1)) & 1
            sign_b = (b >> (WIDTH - 1)) & 1
            sign_r = (result >> (WIDTH - 1)) & 1

            v = (sign_a == sign_b) and (sign_r != sign_a)

        elif txn.op_code == ALUOp.SUB:

            full = a - b
            c = 1 if a >= b else 0
            result = full & MASK

            sign_a = (a >> (WIDTH - 1)) & 1
            sign_b = (b >> (WIDTH - 1)) & 1
            sign_r = (result >> (WIDTH - 1)) & 1

            v = (sign_a != sign_b) and (sign_r != sign_a)

        elif txn.op_code == ALUOp.AND:

            result = a & b

        elif txn.op_code == ALUOp.OR:

            result = a | b

        else:

            result = 0

        # -----------------------
        # Flags
        # -----------------------
        z = int(result == 0)
        n = (result >> (WIDTH - 1)) & 1

        # -----------------------
        # Convert back to signed
        # -----------------------
        if result & (1 << (WIDTH - 1)):
            result -= (1 << WIDTH)
       
        return result, z, n, c, int(v)

        



@cocotb.test()
async def ALU_test(dut):
    # start the clk of the dut 
    cocotb.start_soon(Clock(dut.clk, 10, unit="ns").start())

    driver = Driver(dut)
    monitor = Monitor(dut)
    scoreboard = Scoreboard()

    # connect the monitor and the SB 
    scoreboard.analysis_export = monitor.analysis_port
    
    cocotb.start_soon(driver.run())
    cocotb.start_soon(monitor.run())
    cocotb.start_soon(scoreboard.run())

    # Reset
    await driver.reset_driving()

    txn = Transaction(3, 2, ALUOp.ADD)
    await driver.seq_item_port.put(txn)

    txn = Transaction(5, 2, ALUOp.SUB)
    await driver.seq_item_port.put(txn)

    txn = Transaction(7, 1, ALUOp.AND)
    await driver.seq_item_port.put(txn)

 
    txn = Transaction(4, 1, ALUOp.OR)
    await driver.seq_item_port.put(txn)

    await ClockCycles(dut.clk, 10)
    


    
